### ISSUE TITLE
Review HttpRedirectPolicy variations

### ISSUE THREAD

**Issue by jfallows** [kaazing/netx.http#10]
Perhaps we should simplify as follows:
- `NEVER`
- `ALWAYS`
- `ORIGIN` (a.k.a `SAME_ORIGIN`)
- `DOMAIN` (matches any of `SAME_DOMAIN`, `PEER_DOMAIN` or `SUB_DOMAIN`)

**Comment by sanjay-saxena** [comment]
Yes. It makes sense.

**Comment by sanjay-saxena** [comment]
This is complete.
