### ISSUE TITLE
Rename BasicChallengeHandler to ApplicationBasicChallengeHandler, etc.

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/netx.http#11]
Perhaps we should rename BasicChallengeHandler -> ApplicationBasicChallengeHandler, etc. to avoid confusion. Schemes "Basic", "Digest", and "Negotiate" will be handled by the system Authenticator. Our ChallengeHandler infrastructure will be used only for "Application *" schemes and the app developer will not expect the registered ChallengeHandler to be used when using the he/she uses "Basic", "Digest", or "Negotiate".

**Comment by jfallows** [comment]
Agreed. That would be much clearer.

**Comment by sanjay-saxena** [comment]
This is complete.
