### ISSUE TITLE
Need ability to pass in ChallengeHandler to HttpURLConnection

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/netx.http#13]
Need the getter/setter for ChallengeHandler and then invoke/use the ChallengeHandler in response to 3xx.

**Comment by jfallows** [comment]
Only for `Application Basic`, `Application Digest` and `Application Negotiate` challenges though, right?

The `Basic`, `Digest` and `Negotiate` challenges would flow through the system-wide `Authenticator` mechanism as usual.

**Comment by sanjay-saxena** [comment]
That's right. Note that we also support `Application Token` for custom ChallengeHandler implementations.

**Comment by sanjay-saxena** [comment]
This is now supported.
