### ISSUE TITLE
processChallenges() can moved out of the handler into HttpURLConnectionImpl

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/netx.http#15]
Just like processRedirect(), processChallenges() can be in HttpURLConnectionImpl instead of HttpURLConnectionHandler.Upgradeable. This way, there will not be any code duplication as it can be used by both WS and WSE/SSE.

**Comment by jfallows** [comment]
The built-in implementation is already handling non-Application challenges. 
This code is intended to keep parity for non-Application challenges when responding to an `Upgrade` request.

**Comment by jfallows** [comment]
The Application challenge handling should be in `HttpURLConnectionImpl` though.

**Comment by jfallows** [comment]
If you agree @sanjay-saxena we can close this as wontfix.

**Comment by sanjay-saxena** [comment]
Agreed.
