### ISSUE TITLE
Support connection timeout with ability to pause the timer for credentials

### ISSUE THREAD

**Issue by sanjay-saxena** [kaazing/netx.http#24]
If a login dialog is being shown to the user, then the timer should pause while the dialog is up. Once the user provides the credentials and dismisses the dialog, the timer should resume.

**Comment by sanjay-saxena** [comment]
HttpURLConnection supports setAllowUserInteraction(boolean). However, it is not clear if this will work for `Application *` authentication schemes that are handled outside the purview of the system `java.net.Authenticator`.

**Comment by sbadugu** [comment]
This issue was moved to kaazing/netx#35
